/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppClientesRouteImport } from './routes/_app/clientes'
import { Route as AppCreditosRouteImport } from './routes/_app/creditos'
import { Route as AppGestaoRouteImport } from './routes/_app/gestao'
import { Route as AppProdutosRouteImport } from './routes/_app/produtos'
import { Route as AppUsuariosRouteImport } from './routes/_app/usuarios'
import { Route as AppOdcIndexRouteImport } from './routes/_app/odc/index'
import { Route as AppOdcIdRouteImport } from './routes/_app/odc/$id'
import { Route as AppOdcNovaRouteImport } from './routes/_app/odc/nova'
import { Route as AppVendasIndexRouteImport } from './routes/_app/vendas/index'
import { Route as AppVendasIdRouteImport } from './routes/_app/vendas/$id'
import { Route as AppVendasNovaRouteImport } from './routes/_app/vendas/nova'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppClientesRoute = AppClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => AppRoute,
} as any)
const AppCreditosRoute = AppCreditosRouteImport.update({
  id: '/creditos',
  path: '/creditos',
  getParentRoute: () => AppRoute,
} as any)
const AppGestaoRoute = AppGestaoRouteImport.update({
  id: '/gestao',
  path: '/gestao',
  getParentRoute: () => AppRoute,
} as any)
const AppProdutosRoute = AppProdutosRouteImport.update({
  id: '/produtos',
  path: '/produtos',
  getParentRoute: () => AppRoute,
} as any)
const AppUsuariosRoute = AppUsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => AppRoute,
} as any)
const AppOdcIndexRoute = AppOdcIndexRouteImport.update({
  id: '/odc/',
  path: '/odc/',
  getParentRoute: () => AppRoute,
} as any)
const AppOdcIdRoute = AppOdcIdRouteImport.update({
  id: '/odc/$id',
  path: '/odc/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppOdcNovaRoute = AppOdcNovaRouteImport.update({
  id: '/odc/nova',
  path: '/odc/nova',
  getParentRoute: () => AppRoute,
} as any)
const AppVendasIndexRoute = AppVendasIndexRouteImport.update({
  id: '/vendas/',
  path: '/vendas/',
  getParentRoute: () => AppRoute,
} as any)
const AppVendasIdRoute = AppVendasIdRouteImport.update({
  id: '/vendas/$id',
  path: '/vendas/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppVendasNovaRoute = AppVendasNovaRouteImport.update({
  id: '/vendas/nova',
  path: '/vendas/nova',
  getParentRoute: () => AppRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/login': typeof LoginRoute
  '/clientes': typeof AppClientesRoute
  '/creditos': typeof AppCreditosRoute
  '/gestao': typeof AppGestaoRoute
  '/produtos': typeof AppProdutosRoute
  '/usuarios': typeof AppUsuariosRoute
  '/odc/$id': typeof AppOdcIdRoute
  '/odc/nova': typeof AppOdcNovaRoute
  '/vendas/$id': typeof AppVendasIdRoute
  '/vendas/nova': typeof AppVendasNovaRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/odc/': typeof AppOdcIndexRoute
  '/vendas/': typeof AppVendasIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/clientes': typeof AppClientesRoute
  '/creditos': typeof AppCreditosRoute
  '/gestao': typeof AppGestaoRoute
  '/produtos': typeof AppProdutosRoute
  '/usuarios': typeof AppUsuariosRoute
  '/': typeof AppIndexRoute
  '/odc/$id': typeof AppOdcIdRoute
  '/odc/nova': typeof AppOdcNovaRoute
  '/vendas/$id': typeof AppVendasIdRoute
  '/vendas/nova': typeof AppVendasNovaRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/odc': typeof AppOdcIndexRoute
  '/vendas': typeof AppVendasIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/clientes': typeof AppClientesRoute
  '/_app/creditos': typeof AppCreditosRoute
  '/_app/gestao': typeof AppGestaoRoute
  '/_app/produtos': typeof AppProdutosRoute
  '/_app/usuarios': typeof AppUsuariosRoute
  '/_app/': typeof AppIndexRoute
  '/_app/odc/$id': typeof AppOdcIdRoute
  '/_app/odc/nova': typeof AppOdcNovaRoute
  '/_app/vendas/$id': typeof AppVendasIdRoute
  '/_app/vendas/nova': typeof AppVendasNovaRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/_app/odc/': typeof AppOdcIndexRoute
  '/_app/vendas/': typeof AppVendasIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/clientes'
    | '/creditos'
    | '/gestao'
    | '/produtos'
    | '/usuarios'
    | '/odc/$id'
    | '/odc/nova'
    | '/vendas/$id'
    | '/vendas/nova'
    | '/api/auth/$'
    | '/odc/'
    | '/vendas/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/clientes'
    | '/creditos'
    | '/gestao'
    | '/produtos'
    | '/usuarios'
    | '/'
    | '/odc/$id'
    | '/odc/nova'
    | '/vendas/$id'
    | '/vendas/nova'
    | '/api/auth/$'
    | '/odc'
    | '/vendas'
  id:
    | '__root__'
    | '/_app'
    | '/login'
    | '/_app/clientes'
    | '/_app/creditos'
    | '/_app/gestao'
    | '/_app/produtos'
    | '/_app/usuarios'
    | '/_app/'
    | '/_app/odc/$id'
    | '/_app/odc/nova'
    | '/_app/vendas/$id'
    | '/_app/vendas/nova'
    | '/api/auth/$'
    | '/_app/odc/'
    | '/_app/vendas/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/clientes': {
      id: '/_app/clientes'
      path: '/clientes'
      fullPath: '/clientes'
      preLoaderRoute: typeof AppClientesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/creditos': {
      id: '/_app/creditos'
      path: '/creditos'
      fullPath: '/creditos'
      preLoaderRoute: typeof AppCreditosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/gestao': {
      id: '/_app/gestao'
      path: '/gestao'
      fullPath: '/gestao'
      preLoaderRoute: typeof AppGestaoRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/produtos': {
      id: '/_app/produtos'
      path: '/produtos'
      fullPath: '/produtos'
      preLoaderRoute: typeof AppProdutosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/usuarios': {
      id: '/_app/usuarios'
      path: '/usuarios'
      fullPath: '/usuarios'
      preLoaderRoute: typeof AppUsuariosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/odc/': {
      id: '/_app/odc/'
      path: '/odc'
      fullPath: '/odc/'
      preLoaderRoute: typeof AppOdcIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/odc/$id': {
      id: '/_app/odc/$id'
      path: '/odc/$id'
      fullPath: '/odc/$id'
      preLoaderRoute: typeof AppOdcIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/odc/nova': {
      id: '/_app/odc/nova'
      path: '/odc/nova'
      fullPath: '/odc/nova'
      preLoaderRoute: typeof AppOdcNovaRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/vendas/': {
      id: '/_app/vendas/'
      path: '/vendas'
      fullPath: '/vendas/'
      preLoaderRoute: typeof AppVendasIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/vendas/$id': {
      id: '/_app/vendas/$id'
      path: '/vendas/$id'
      fullPath: '/vendas/$id'
      preLoaderRoute: typeof AppVendasIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/vendas/nova': {
      id: '/_app/vendas/nova'
      path: '/vendas/nova'
      fullPath: '/vendas/nova'
      preLoaderRoute: typeof AppVendasNovaRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppRouteChildren {
  AppClientesRoute: typeof AppClientesRoute
  AppCreditosRoute: typeof AppCreditosRoute
  AppGestaoRoute: typeof AppGestaoRoute
  AppProdutosRoute: typeof AppProdutosRoute
  AppUsuariosRoute: typeof AppUsuariosRoute
  AppIndexRoute: typeof AppIndexRoute
  AppOdcIdRoute: typeof AppOdcIdRoute
  AppOdcNovaRoute: typeof AppOdcNovaRoute
  AppVendasIdRoute: typeof AppVendasIdRoute
  AppVendasNovaRoute: typeof AppVendasNovaRoute
  AppOdcIndexRoute: typeof AppOdcIndexRoute
  AppVendasIndexRoute: typeof AppVendasIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppClientesRoute: AppClientesRoute,
  AppCreditosRoute: AppCreditosRoute,
  AppGestaoRoute: AppGestaoRoute,
  AppProdutosRoute: AppProdutosRoute,
  AppUsuariosRoute: AppUsuariosRoute,
  AppIndexRoute: AppIndexRoute,
  AppOdcIdRoute: AppOdcIdRoute,
  AppOdcNovaRoute: AppOdcNovaRoute,
  AppVendasIdRoute: AppVendasIdRoute,
  AppVendasNovaRoute: AppVendasNovaRoute,
  AppOdcIndexRoute: AppOdcIndexRoute,
  AppVendasIndexRoute: AppVendasIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
